[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-T/Users/keefereeves/Desktop/oreulia/kernel/kernel.ld",
    "-C", "relocation-model=static",
    "-C", "code-model=kernel"
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
